In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset = pd.read_csv('Data.csv', delimiter=';')
x = dataset.iloc [:, :-1] . values
y= dataset.iloc [:, -1] .values


In [3]:
print (dataset)

   Country DEAD   Age   Salary Purchased
0   France  YES  44.0  72000.0        No
1    Spain   NO  27.0  48000.0       Yes
2  Germany   NO  30.0  54000.0        No
3    Spain   NO  38.0  61000.0        No
4  Germany  YES  40.0      NaN       Yes
5   France   NO  35.0  58000.0       Yes
6    Spain   NO   NaN  52000.0        No
7   France  YES  48.0  79000.0       Yes
8  Germany  YES  50.0  83000.0        No
9   France   NO  37.0  67000.0       Yes


In [4]:
print(x)

[['France' 'YES' 44.0 72000.0]
 ['Spain' 'NO' 27.0 48000.0]
 ['Germany' 'NO' 30.0 54000.0]
 ['Spain' 'NO' 38.0 61000.0]
 ['Germany' 'YES' 40.0 nan]
 ['France' 'NO' 35.0 58000.0]
 ['Spain' 'NO' nan 52000.0]
 ['France' 'YES' 48.0 79000.0]
 ['Germany' 'YES' 50.0 83000.0]
 ['France' 'NO' 37.0 67000.0]]


In [5]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:4])
x[:, 1:3] = imputer.transform(x[:, 2:4])

In [7]:
print (x)

[['France' 44.0 72000.0 72000.0]
 ['Spain' 27.0 48000.0 48000.0]
 ['Germany' 30.0 54000.0 54000.0]
 ['Spain' 38.0 61000.0 61000.0]
 ['Germany' 40.0 63777.77777777778 nan]
 ['France' 35.0 58000.0 58000.0]
 ['Spain' 38.77777777777778 52000.0 52000.0]
 ['France' 48.0 79000.0 79000.0]
 ['Germany' 50.0 83000.0 83000.0]
 ['France' 37.0 67000.0 67000.0]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers=[('encorder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print (x)

[[0.0 1.0 0.0 0.0 44.0 72000.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778 nan]
 [0.0 1.0 0.0 0.0 35.0 58000.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0 67000.0]]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print (y)

[0 1 0 0 1 1 0 1 0 1]


In [13]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print (x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
